spring:
  application:
    name: safaricomTopupIntegration
server:
  port: 3070
  address: 10.1.22.176

#  ssl:
#    enabled: true
#    key-store: classpath:new_keystore.p12
#    #C:\Users\abenezert\Downloads\_blueprint_safaricom_et\new_keystore.p12
#    key-store-password: changeit
#    key-store-type: pkcs12
#    keyAlias: safaricert  # Use the alias 'safaricert' here
dxl:
  trust-store: C:\Users\abenezert\Downloads\_blueprint_safaricom_et\new_keystore.p12
  password: changeit

api:
  token:
    url: https://blueprint.safaricom.et:7001/v1/token
    ttl:
      minutes: 10
  username: PRETUPS
  password: MRyhsEPWzO8jDqaE0EAKnw==
  base-url: https://blueprint.safaricom.et:7001



  #    trust-store: C:\Users\abenezert\Downloads\_blueprint_safaricom_et\topup_converted.jks
  #    trust-store-password: changeit
  #    trust-store-type: JKS
  #    trust-store-provider: SUN
  #    enabled: true
  #    certificate: classpath:blueprint_safaricom_et.crt
  #    key-store: classpath:topup.jks
  #    key-alias: safaricert
#    client:
#      truststore:
#        certificate: classpath:blueprint_safaricom_et.crt




logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    org.springframework.http.client.reactive.ReactorClientHttpConnector: DEBUG
    org.apache.http: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client.HttpClient: DEBUG

  # Optional: you can also enable logging for specific classes/methods
  # For full HTTP request/response logging, include this:
  loggers:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.web.reactive.function.client.WebClient: DEBUG
    reactor.netty.channel: DEBUG
    reactor.netty.transport: DEBUG

